### ISSUE TITLE
Import CSV file with multiple entity references 

### ISSUE THREAD

**Issue by lucasIPK** [loefel/opensourcedesign#1]
For some of the products, the License field has multiple entries.
We need to find the right yml configuration to manage this possibility by finding the right plugin.

Here some help:
https://drupal.stackexchange.com/questions/214450/drupal-migrate-source-csv
https://makina-corpus.com/blog/metier/2016/utiliser-migrate-en-drupal-8

**Comment by loefel** [comment]
Check out: http://stackoverflow.com/questions/3853614/multiple-values-for-one-field-with-comma-separated-values-csv-format
