### ISSUE TITLE
Issues (Excel File)

### ISSUE THREAD

**Issue by lucasIPK** [loefel/opensourcedesign#11]
[Issue list v6.xlsx](https://github.com/loefel/opensourcedesign/files/1047622/Issue.list.v6.xlsx)

**Comment by lucasIPK** [comment]
[Issue list v6.xlsx](https://github.com/loefel/opensourcedesign/files/1114695/Issue.list.v6.xlsx)
some issues still remain in this file I updated

**Comment by loefel** [comment]
created open issues here
