### ISSUE TITLE
Wrong redirection of the comments

### ISSUE THREAD

**Issue by lucasIPK** [loefel/opensourcedesign#2]
When I created the view mode "Comment view" and then used it in the view "Comment page", the comment linked to the main view tab of the product (drupal/node/{id}) and not to the comment tab (drupal/node/{id}/comments).
I already created a hook which changes the url of the permalink of the comments but there is an other way I think to resolve this issue (I need to show it to explain).
There is also the redirection of the submit which needs to be modified.

**Comment by loefel** [comment]
The Rules module may be used, but it's currently broken:
https://www.drupal.org/project/rules

**Comment by lucasIPK** [comment]
Maybe try:
https://www.drupal.org/node/2023537
=> Altering the redirection URL:
=> D8

**Comment by lucasIPK** [comment]
everything works !
