### ISSUE TITLE
Footer not displaying

### ISSUE THREAD

**Issue by lucasIPK** [loefel/opensourcedesign#26]
When i try to place a block in the footer, it isn't displayed

**Comment by jbon** [comment]
the footer should display the license under which the contents are published and is therefore very important. Please add to the footer the following text:

>  All content of this website are published under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). Please feel free to contribute to this work!

and add the icon to be found here: https://creativecommons.org/choose/?lang=en

**Comment by loefel** [comment]
Footer is now showing.
