### ISSUE TITLE
[minor corrections]

### ISSUE THREAD

**Issue by jbon** [loefel/opensourcedesign#28]
- [x] Replace title "Report page" with "Report inappropriate content"
- [x] The URL of the report page is https://opensourcedesign.cc/observatory/**contact**. Replace with https://opensourcedesign.cc/observatory/report
- [x] The menu where the links "main page", "add product" and "report" are displayed is named inappropriately "Tools". Rename "Menu"
- [x] In this same menu, replace "Main page" with "Homepage"
- [x] The attribute „development stage“ of the object "product" is now called „maturity“. Please replace each time this attribute appears, for example in the header of the table on the homepage and in the product detail page.
- [x] In page "create new account", replace "revision notification" with "Do you want to be notified each time your contributions have been edited by someone else?"
- [x] In the mail sent for reseting a password, replace the subject "Replacement login information for \<login\> at Open source design" with "[Observatory of Open Source Hardware] Reset your password"
- [x] In the mail sent for reseting a password, replace the text "A request to reset the password for your account has been made at Open source design." with "We recieved a request to reset the password of your account at the Observatory of Open Source Hardware."
- [x] In the mail sent for reseting a password, replace the signature "Open source design team" with "Administration team of the Observatory of Open Source Hardware"
- [x] In the confirmation mail sent after validating the report form, replace the subject "[Report page] \<title\>" with "[Observatory of Open Source Hardware] Report confirmation"
- [x] In the confirmation mail sent after validating the report form, replace the text "\<login\> (\<userpage\>) sent a message using the contact form at https://opensourcedesign.cc/observatory/contact" with "\<user\> (\<userpage\>) reported inappropriate content using the report form at https://opensourcedesign.cc/observatory/report"

**Comment by loefel** [comment]
Fixed all but the last two.

**Comment by jbon** [comment]
Can you please tick the boxes accordingly?
