### ISSUE TITLE
Field "revision notification" in first login page is useless and should be removed

### ISSUE THREAD

**Issue by jbon** [loefel/opensourcedesign#31]
- [ ] this field has already filled out by the user at the user creation. there is no use of asking for it a second tiem while logging in for the first time.
- [x]  Also: after validating the password change at the first login, there is no redirection. Please redirect to the home page

**Comment by jbon** [comment]
Also: after validating the password change at the first login, there is no redirection. Please redirect to the home page

**Comment by loefel** [comment]
The first login page is the default user edit page. It should be possible to change whether or not to receive revision notifications on the default user edit page.
