### ISSUE TITLE
Create the field Editable CAD

### ISSUE THREAD

**Issue by lucasIPK** [loefel/opensourcedesign#4]
A product might have several CAD files. 
Each CAD file has a boolean value associated to it which gives the editability of the CAD file.
If one of the CAD files of the product is editable then we say that the whole product has editable CAD files.

We need to implement this field so it is calculated automaticaly.

**Comment by lucasIPK** [comment]
make the field sortable

**Comment by lucasIPK** [comment]
change the open-o-meter based on this field

**Comment by loefel** [comment]
A field type "Editable CAD formats" has been created and added to the content type "Product". It works like a boolean field, except it can't be set in the edit form. Instead it is set in the preSave function in the file open_o_meter\Plugin\Field\FieldType\EditableCADField.php. Unfortunately it's not being set to the correct value, yet.

**Comment by loefel** [comment]
The open-o-meter has been changed and the field made sortable.
